apiVersion: v1
kind: ConfigMap
metadata:
  name: zeebe-config
  labels:
    app: zeebe-config
data:
  zeebe.cfg.toml: |
    [[exporters]]
    id = "elasticsearch"
    className = "io.zeebe.exporter.ElasticsearchExporter"

      [exporters.args]
      url = "http://elastic-rest:9200"

      [exporters.args.bulk]
      delay = 1
      size = 1

      [exporters.args.index]
      prefix = "operate"
      createTemplate = true
      command = false
      event = true
      rejection = false
      deployment = true
      incident = true
      job = true
      message = false
      messageSubscription = false
      raft = false
      workflowInstance = true
      workflowInstanceSubscription = false
